In [90]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")
  
SWI = pd.read_csv('./SWI20210101DATASET.csv')
print('The shape of the dataset is:', SWI.shape)

The shape of the dataset is: (375, 102)

In [91]:
SWI.head(5)

,Unnamed: 0,801950.SWI,801160.SWI,801720.SWI,801730.SWI,801880.SWI,801010,801740,801050,801970.SWI,...,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100,Unnamed: 101
0,2022-07-21,2871.494,2871.494,Error,11910.17,6592.130,3648.164,1620.953,5454.566,1994.697,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-07-20,2983.299,2471.412,2187.962,12059.92,6626.311,3652.703,1651.778,5563.898,2016.265,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-07-19,2998.265,2470.070,2184.337,12001.52,6641.441,3685.353,1579.964,5500.921,2011.236,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-07-18,3003.499,2492.043,2179.823,12302.08,6627.475,3677.841,1568.915,5488.091,2021.686,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-07-15,2883.407,2424.085,2139.722,12158.48,6484.478,3659.993,1564.073,5377.002,1932.918,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
SWI = SWI.drop(SWI.columns[32:,], axis=1)

In [95]:
SWI.head(10)

,Unnamed: 0,801950.SWI,801160.SWI,801720.SWI,801730.SWI,801880.SWI,801010,801740,801050,801970.SWI,...,801130,801760,801780,801110,801790,801210,801150,801980,801750,801080
0,2022-07-21,2871.494,2871.494,Error,11910.17,6592.130,3648.164,1620.953,5454.566,1994.697,...,1626.108,556.419,3124.129,7011.965,1489.770,9762.069,9512.924,7377.255,3911.972,4024.719
1,2022-07-20,2983.299,2471.412,2187.962,12059.92,6626.311,3652.703,1651.778,5563.898,2016.265,...,1634.787,552.504,3179.822,7075.451,1506.755,9795.913,9537.325,7433.764,3926.570,3985.942
2,2022-07-19,2998.265,2470.070,2184.337,12001.52,6641.441,3685.353,1579.964,5500.921,2011.236,...,1616.341,548.840,3165.273,7050.679,1506.440,9620.642,9414.492,7212.360,3898.668,3956.619
3,2022-07-18,3003.499,2492.043,2179.823,12302.08,6627.475,3677.841,1568.915,5488.091,2021.686,...,1599.431,537.546,3151.364,7073.164,1499.204,9590.062,9479.349,7205.198,3797.636,3939.122
4,2022-07-15,2883.407,2424.085,2139.722,12158.48,6484.478,3659.993,1564.073,5377.002,1932.918,...,1568.364,524.142,3108.494,6987.161,1466.224,9525.596,9456.226,7099.412,3696.810,3904.603
5,2022-07-14,2912.002,2459.546,2214.273,12327.88,6393.822,3748.998,1586.543,5458.171,1952.783,...,1610.078,536.777,3184.794,7070.199,1505.379,9575.105,9680.617,7106.321,3781.545,3922.524
6,2022-07-13,2917.184,2499.926,2239.727,11958.24,6254.967,3775.414,1550.436,5437.433,1954.938,...,1610.815,537.917,3254.113,7225.118,1525.575,9501.335,9524.800,7041.771,3773.347,3881.746
7,2022-07-12,2939.371,2459.801,2216.116,11597.24,6209.279,3762.069,1558.641,5418.399,1917.901,...,1599.023,532.302,3333.757,7262.355,1531.637,9441.529,9548.431,6945.192,3752.903,3904.600
8,2022-07-11,2915.948,2454.653,2178.775,11752.47,6352.863,3862.850,1581.551,5508.325,1930.594,...,1624.695,538.839,3345.016,7204.254,1528.388,9581.790,9837.729,7070.930,3819.303,4003.493
9,2022-07-08,3055.723,2435.740,2171.571,12019.74,6542.268,3795.094,1599.659,5714.775,1940.508,...,1648.739,548.136,3348.661,7155.190,1544.667,9761.657,9855.902,7196.556,3891.628,4101.957

In [100]:
SWI.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 32 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  375 non-null    object
 1   801950.SWI  375 non-null    float64
 2   801160.SWI  375 non-null    float64
 3   801720.SWI  375 non-null    object
 4   801730.SWI  375 non-null    float64
 5   801880.SWI  375 non-null    float64
 6   801010      375 non-null    float64
 7   801740      375 non-null    float64
 8   801050      375 non-null    float64
 9   801970.SWI  375 non-null    float64
 10  801170      375 non-null    float64
 11  801770      375 non-null    float64
 12  801030      375 non-null    float64
 13  801890      375 non-null    float64
 14  801960      375 non-null    float64
 15  801230      375 non-null    float64
 16  801040      375 non-null    float64
 17  801200      375 non-null    float64
 18  801120      375 non-null    float64
 19  801180      375 non-null    float64
 20  801710      375 non-null    float64
 21  801140      375 non-null    float64
 22  801130      375 non-null    float64
 23  801760      375 non-null    float64
 24  801780      375 non-null    float64
 25  801110      375 non-null    float64
 26  801790      375 non-null    float64
 27  801210      375 non-null    float64
 28  801150      375 non-null    float64
 29  801980      375 non-null    float64
 30  801750      375 non-null    float64
 31  801080      375 non-null    float64
dtypes: float64(30), object(2)
memory usage: 93.9+ KB

In [101]:
data_code = list(SWI.columns)
data_code.remove("Unnamed: 0")
data_code

['801950.SWI',
 '801160.SWI',
 '801720.SWI',
 '801730.SWI',
 '801880.SWI',
 '801010',
 '801740',
 '801050',
 '801970.SWI',
 '801170',
 '801770',
 '801030',
 '801890',
 '801960',
 '801230',
 '801040',
 '801200',
 '801120',
 '801180',
 '801710',
 '801140',
 '801130',
 '801760',
 '801780',
 '801110',
 '801790',
 '801210',
 '801150',
 '801980',
 '801750',
 '801080']

In [103]:
SWI = SWI.drop(SWI.columns[0,],axis=1) 
SWI.head(10)

,801950.SWI,801160.SWI,801720.SWI,801730.SWI,801880.SWI,801010,801740,801050,801970.SWI,801170,...,801130,801760,801780,801110,801790,801210,801150,801980,801750,801080
0,2871.494,2871.494,2187.962,11910.17,6592.130,3648.164,1620.953,5454.566,1994.697,2345.487,...,1626.108,556.419,3124.129,7011.965,1489.770,9762.069,9512.924,7377.255,3911.972,4024.719
1,2983.299,2471.412,2187.962,12059.92,6626.311,3652.703,1651.778,5563.898,2016.265,2357.213,...,1634.787,552.504,3179.822,7075.451,1506.755,9795.913,9537.325,7433.764,3926.570,3985.942
2,2998.265,2470.070,2184.337,12001.52,6641.441,3685.353,1579.964,5500.921,2011.236,2342.785,...,1616.341,548.840,3165.273,7050.679,1506.440,9620.642,9414.492,7212.360,3898.668,3956.619
3,3003.499,2492.043,2179.823,12302.08,6627.475,3677.841,1568.915,5488.091,2021.686,2317.951,...,1599.431,537.546,3151.364,7073.164,1499.204,9590.062,9479.349,7205.198,3797.636,3939.122
4,2883.407,2424.085,2139.722,12158.48,6484.478,3659.993,1564.073,5377.002,1932.918,2281.533,...,1568.364,524.142,3108.494,6987.161,1466.224,9525.596,9456.226,7099.412,3696.810,3904.603
5,2912.002,2459.546,2214.273,12327.88,6393.822,3748.998,1586.543,5458.171,1952.783,2333.409,...,1610.078,536.777,3184.794,7070.199,1505.379,9575.105,9680.617,7106.321,3781.545,3922.524
6,2917.184,2499.926,2239.727,11958.24,6254.967,3775.414,1550.436,5437.433,1954.938,2338.388,...,1610.815,537.917,3254.113,7225.118,1525.575,9501.335,9524.800,7041.771,3773.347,3881.746
7,2939.371,2459.801,2216.116,11597.24,6209.279,3762.069,1558.641,5418.399,1917.901,2302.828,...,1599.023,532.302,3333.757,7262.355,1531.637,9441.529,9548.431,6945.192,3752.903,3904.600
8,2915.948,2454.653,2178.775,11752.47,6352.863,3862.850,1581.551,5508.325,1930.594,2313.112,...,1624.695,538.839,3345.016,7204.254,1528.388,9581.790,9837.729,7070.930,3819.303,4003.493
9,3055.723,2435.740,2171.571,12019.74,6542.268,3795.094,1599.659,5714.775,1940.508,2339.762,...,1648.739,548.136,3348.661,7155.190,1544.667,9761.657,9855.902,7196.556,3891.628,4101.957

In [104]:
print(SWI.iat[1,1])
print(SWI.iat[1,0])
type(SWI.iat[1,0])

2471.4120000000003
2983.2990000000004

numpy.float64

In [105]:
SWI['801720.SWI'] = SWI['801720.SWI'].replace(['Error'],'2187.962')
SWI.head(5)

,801950.SWI,801160.SWI,801720.SWI,801730.SWI,801880.SWI,801010,801740,801050,801970.SWI,801170,...,801130,801760,801780,801110,801790,801210,801150,801980,801750,801080
0,2871.494,2871.494,2187.962,11910.17,6592.130,3648.164,1620.953,5454.566,1994.697,2345.487,...,1626.108,556.419,3124.129,7011.965,1489.770,9762.069,9512.924,7377.255,3911.972,4024.719
1,2983.299,2471.412,2187.962,12059.92,6626.311,3652.703,1651.778,5563.898,2016.265,2357.213,...,1634.787,552.504,3179.822,7075.451,1506.755,9795.913,9537.325,7433.764,3926.570,3985.942
2,2998.265,2470.070,2184.337,12001.52,6641.441,3685.353,1579.964,5500.921,2011.236,2342.785,...,1616.341,548.840,3165.273,7050.679,1506.440,9620.642,9414.492,7212.360,3898.668,3956.619
3,3003.499,2492.043,2179.823,12302.08,6627.475,3677.841,1568.915,5488.091,2021.686,2317.951,...,1599.431,537.546,3151.364,7073.164,1499.204,9590.062,9479.349,7205.198,3797.636,3939.122
4,2883.407,2424.085,2139.722,12158.48,6484.478,3659.993,1564.073,5377.002,1932.918,2281.533,...,1568.364,524.142,3108.494,6987.161,1466.224,9525.596,9456.226,7099.412,3696.810,3904.603

In [106]:
SWI.shape[0]
row_length = range(SWI.shape[0]-1)
column_length = range(SWI.shape[1])

In [122]:


total_profit_rate = []
for n in column_length:
    k = 1
    for i in row_length:
        profit_rate_day = ((float(SWI.iat[374-(i+1),n])-float(SWI.iat[374-i,n]))/float(SWI.iat[374-i,n])) + 1
        k = k*profit_rate_day
    print(k-1)
    total_profit_rate.append(k-1)

0.6309746677269086
0.4292617249231572
0.13748585266390867
0.30835326044448674
0.12679645879744528
-0.12751485884456315
-0.14069294706334812
0.2635760681194641
0.04940971601132227
-0.029106677986574625
-0.061675791556266235
0.23623768396346345
-0.01079419332663134
0.09578229274803474
0.11166866411649812
0.15728721360822417
-0.14091054562037952
-0.18302111613773964
-0.194454266516094
-0.1363836498805514
-0.11966426867574587
-0.08475680969440436
-0.24737659372438636
-0.13880704892057505
-0.321992049901326
-0.34205371878744284
-0.225033957117579
-0.21165921660857423
-0.07576938255210086
-0.25159472492943946
-0.1625641931559353

In [127]:
total_profit_rate[1]

0.4292617249231572

In [136]:
Final_rate_t = pd.DataFrame(list(zip(data_code, total_profit_rate)), columns=["windcode","Final Profit Rate"]) 
    

print(Final_rate_t)

      windcode  Final Profit Rate
0   801950.SWI           0.630975
1   801160.SWI           0.429262
2   801720.SWI           0.137486
3   801730.SWI           0.308353
4   801880.SWI           0.126796
5       801010          -0.127515
6       801740          -0.140693
7       801050           0.263576
8   801970.SWI           0.049410
9       801170          -0.029107
10      801770          -0.061676
11      801030           0.236238
12      801890          -0.010794
13      801960           0.095782
14      801230           0.111669
15      801040           0.157287
16      801200          -0.140911
17      801120          -0.183021
18      801180          -0.194454
19      801710          -0.136384
20      801140          -0.119664
21      801130          -0.084757
22      801760          -0.247377
23      801780          -0.138807
24      801110          -0.321992
25      801790          -0.342054
26      801210          -0.225034
27      801150          -0.211659
28      801980          -0.075769
29      801750          -0.251595
30      801080          -0.162564

In [158]:
Final_rate_t.to_csv('Final_rate_table.csv')

In [141]:
SWI2 = pd.read_csv('./SWI20210101DATASET.csv')
SWI2 = SWI2.drop(SWI2.columns[32:,], axis=1) 
SWI2.head(5)

,Unnamed: 0,801950.SWI,801160.SWI,801720.SWI,801730.SWI,801880.SWI,801010,801740,801050,801970.SWI,...,801130,801760,801780,801110,801790,801210,801150,801980,801750,801080
0,2022-07-21,2871.494,2871.494,Error,11910.17,6592.130,3648.164,1620.953,5454.566,1994.697,...,1626.108,556.419,3124.129,7011.965,1489.770,9762.069,9512.924,7377.255,3911.972,4024.719
1,2022-07-20,2983.299,2471.412,2187.962,12059.92,6626.311,3652.703,1651.778,5563.898,2016.265,...,1634.787,552.504,3179.822,7075.451,1506.755,9795.913,9537.325,7433.764,3926.570,3985.942
2,2022-07-19,2998.265,2470.070,2184.337,12001.52,6641.441,3685.353,1579.964,5500.921,2011.236,...,1616.341,548.840,3165.273,7050.679,1506.440,9620.642,9414.492,7212.360,3898.668,3956.619
3,2022-07-18,3003.499,2492.043,2179.823,12302.08,6627.475,3677.841,1568.915,5488.091,2021.686,...,1599.431,537.546,3151.364,7073.164,1499.204,9590.062,9479.349,7205.198,3797.636,3939.122
4,2022-07-15,2883.407,2424.085,2139.722,12158.48,6484.478,3659.993,1564.073,5377.002,1932.918,...,1568.364,524.142,3108.494,6987.161,1466.224,9525.596,9456.226,7099.412,3696.810,3904.603

In [148]:
list_of_date = SWI2['Unnamed: 0'].tolist()

'2021-01-04'

In [151]:
Profit_rate_table = pd.DataFrame(columns=data_code, index = list_of_date)

In [159]:
for n in column_length:
    rate = 1
    Profit_rate_table.loc[list_of_date[374], data_code[n]] = rate
    k = 1
    for i in row_length:
        profit_rate_day = ((float(SWI.iat[374-(i+1),n])-float(SWI.iat[374-i,n]))/float(SWI.iat[374-i,n])) + 1
        k = k*profit_rate_day
        rate = k-1
        Profit_rate_table.loc[list_of_date[374-i-1], data_code[n]] = rate

In [160]:
Profit_rate_table

,801950.SWI,801160.SWI,801720.SWI,801730.SWI,801880.SWI,801010,801740,801050,801970.SWI,801170,...,801130,801760,801780,801110,801790,801210,801150,801980,801750,801080
2022-07-21,0.630975,0.429262,0.137486,0.308353,0.126796,-0.127515,-0.140693,0.263576,0.0494097,-0.0291067,...,-0.0847568,-0.247377,-0.138807,-0.321992,-0.342054,-0.225034,-0.211659,-0.0757694,-0.251595,-0.162564
2022-07-20,0.694479,0.230124,0.137486,0.324804,0.132639,-0.126429,-0.124352,0.288903,0.0607566,-0.0242528,...,-0.0798719,-0.252672,-0.123455,-0.315853,-0.334552,-0.222347,-0.209637,-0.0686899,-0.248802,-0.170633
2022-07-19,0.702979,0.229456,0.135601,0.318388,0.135225,-0.118621,-0.162422,0.274314,0.0581109,-0.0302251,...,-0.0902541,-0.257628,-0.127465,-0.318249,-0.334692,-0.236261,-0.219816,-0.0964276,-0.25414,-0.176734
2022-07-18,0.705952,0.240393,0.133255,0.351405,0.132838,-0.120417,-0.16828,0.271342,0.0636086,-0.040505,...,-0.0997718,-0.272905,-0.131299,-0.316075,-0.337887,-0.238689,-0.214442,-0.0973249,-0.273469,-0.180375
2022-07-15,0.637741,0.206568,0.112407,0.335631,0.108395,-0.124686,-0.170846,0.245608,0.0169078,-0.0555799,...,-0.117258,-0.291035,-0.143117,-0.32439,-0.352453,-0.243806,-0.216358,-0.110578,-0.292758,-0.187557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-08,-0.0156992,-0.0193711,-0.0112336,0.016136,0.013735,0.0248803,0.00837173,0.0495933,-0.0316133,-0.00936003,...,-0.0351265,-0.0117989,0.0289712,0.0328031,0.00360646,-0.0162327,0.0296991,0.0216636,-0.0319023,0.0323485
2021-01-07,-0.0185278,-0.0235865,-0.019126,0.033245,0.000940118,0.046293,0.0407607,0.0511246,-0.0464125,-0.0145484,...,-0.0409181,-0.0415227,0.0237717,0.0378311,0.00940655,0.0318447,0.0288994,0.0244298,-0.0492095,0.0262006
2021-01-06,-0.0293707,-0.0075602,0.00480373,0.0041156,-0.0108818,0.039235,0.0235206,0.0130709,-0.0194236,-0.00232055,...,-0.0127557,-0.0157053,0.0124846,0.0179385,0.000636849,-0.0181959,0.0304499,0.0331181,-0.0171386,0.0227037
2021-01-05,-0.0221288,-0.0137889,-0.00152378,0.00537494,-0.000272292,0.0367539,0.00754049,0.00846837,-0.0104168,0.00962454,...,-0.00885408,-0.00987413,-0.0121543,0.0273748,-0.0052264,-0.00211245,0.0161241,0.0333824,0.00542521,0.0387203
2021-01-04,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [161]:
Profit_rate_table.to_csv('Profit_rate_table.csv')